sudo: false

language: php

cache:
  directories:
    - .Build/vendor
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - composer require-typo3-version "$TYPO3"
  - git checkout .
  - export TYPO3_PATH_ROOT=$PWD/.Build/public

script:
  - >
    echo;
    echo "Linting all PHP files";
    composer ci:php:lint;

  - >
    echo;
    echo "Linting all TypoScript files";
    composer ci:ts:lint;

jobs:
  include:
    - stage: test
      php: "7.0"
      env: TYPO3=^8.7
    - stage: test
      php: "7.1"
      env: TYPO3=^8.7
    - stage: test
      php: "7.2"
      env: TYPO3=^8.7
    - stage: test
      php: "7.3"
      env: TYPO3=^8.7
    - stage: test
      php: "7.2"
      env: TYPO3=^9.5
    - stage: test
      php: "7.3"
      env: TYPO3=^9.5
