---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '15 3 * * 1'

jobs:
  php-lint:
    name: "PHP linter"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
      - name: "Run PHP lint"
        run: "composer ci:php:lint"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - 8.2

  typoscript-lint:
    name: "TypoScript linter"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Run TypoScript lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-Typoscript-Lint@v1

  yaml-lint:
    name: "YAML linter"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Run YAML lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-YAML-Lint@v1

  json-lint:
    name: "JSON linter"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Run JSON lint"
        uses: TYPO3-Continuous-Integration/TYPO3-CI-JSON-Lint@v1

  code-quality:
    name: "Code quality checks"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2.3
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v3
        with:
          key: "php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-composer-\n"
      - name: "Install Composer dependencies"
        run: "composer install --no-progress"
      - name: "Run command"
        run: "composer ci:${{ matrix.command }}"
    strategy:
      fail-fast: false
      matrix:
        command:
          - "composer:normalize"
        php-version:
          - 8.1

  typo3-install:
    name: "Install with TYPO3"
    runs-on: ubuntu-22.04
    needs: php-lint
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2.3
      - name: "Show Composer version"
        run: composer --version
      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v3
        with:
          key: "php${{ matrix.php-version }}-typo3${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-${{ hashFiles('**/composer.json') }}"
          path: ~/.cache/composer
          restore-keys: "php${{ matrix.php-version }}-typo3${{ matrix.typo3-version }}-${{ matrix.composer-dependencies }}-composer-\n"
      - name: "Install TYPO3 Core"
        env:
          TYPO3: "${{ matrix.typo3-version }}"
        run: |
          composer require --no-ansi --no-interaction --no-progress --no-install typo3/minimal:"$TYPO3"
          composer show
      - name: "Install lowest dependencies with composer"
        if: "matrix.composer-dependencies == 'lowest'"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies --prefer-lowest
          composer show
      - name: "Install highest dependencies with composer"
        if: "matrix.composer-dependencies == 'highest'"
        run: |
          composer update --no-ansi --no-interaction --no-progress --with-dependencies
          composer show
    strategy:
      fail-fast: false
      matrix:
        include:
          - typo3-version: ^10.4
            php-version: 7.2
            composer-dependencies: highest
          - typo3-version: ^10.4
            php-version: 7.2
            composer-dependencies: lowest
          - typo3-version: ^10.4
            php-version: 7.3
            composer-dependencies: highest
          - typo3-version: ^10.4
            php-version: 7.3
            composer-dependencies: lowest
          - typo3-version: ^10.4
            php-version: 7.4
            composer-dependencies: highest
          - typo3-version: ^10.4
            php-version: 7.4
            composer-dependencies: lowest
          - typo3-version: ^11.5
            php-version: 7.4
            composer-dependencies: highest
          - typo3-version: ^11.5
            php-version: 7.4
            composer-dependencies: lowest
          - typo3-version: ^11.5
            php-version: 8.0
            composer-dependencies: highest
          - typo3-version: ^11.5
            php-version: 8.0
            composer-dependencies: lowest
          - typo3-version: ^11.5
            php-version: 8.1
            composer-dependencies: highest
          - typo3-version: ^11.5
            php-version: 8.1
            composer-dependencies: lowest
          - typo3-version: ^11.5
            php-version: 8.2
            composer-dependencies: highest
          - typo3-version: ^11.5
            php-version: 8.2
            composer-dependencies: lowest
